/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nuevo_proyecto;

import java.util.HashSet;
import java.util.Set;

public class App {

    public static void main(String[] args) {
        
        Set<MiClase> set = new HashSet<>();

        set.add(new MiClase(1, "Murcia"));
        set.add(new MiClase(3, "Granada"));
        set.add(new MiClase(1, "Segovia"));
        set.add(new MiClase(11, "Vigo"));
        set.add(new MiClase(10, "Sevilla"));
        set.add(new MiClase(1, "Murcia"));
        set.add(new MiClase(12, "Valencia"));

        System.out.println(set.toString());

        MiClase obje = new MiClase(3, "Granada");

        for (MiClase obj : set) {

            if (obj.equals(obje)) {

                obj.setNum(33);

            }
        }

        System.out.println(set.toString());

        obje = new MiClase(33, "Granada");

        if (set.contains(obje)) {

            System.out.println("El objeto " + obje + " está en el conjunto");

        } else {

            System.out.println("El objeto " + obje + " no está en el conjunto");

        }

    }
}
